import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import logOut from "../lib/components/logOut";
import LogOut from "../lib/components/logOut";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="wrapper">
          <header>
            <nav>
              <Link href={"/ACADEMY"}>ACADEMY</Link>
              <Link href={"/SHOP"}>SHOP</Link>
              {!!session && <LogOut />}
              {!session && <Link href={"/ACADEMY/LOGIN"}>LOG IN</Link>}
            </nav>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
